### ISSUE TITLE
Script timeout

### ISSUE THREAD

**Issue by Peppito** [derekantrican/Google-Apps-Script-Library#12]
The main function will always time-out (after around 360secs) once coming to this line:
`var events = component.getAllSubcomponents("vevent").map(ConvertToCustomEvent);`
Can you please help?

**Comment by derekantrican** [comment]
@Peppito Is there an error message? Please look into recent issues that have also been reported on the same subject: #39, #46, #29 (just to name a couple) may be related to your issue. If any of those solve your issue, please come back and close this issue

**Comment by derekantrican** [comment]
@Peppito which script is this for? This repository has many different scripts

**Comment by Peppito** [comment]
Sorry, now i see that i created it under the root. GAS-ICS-Sync script. No error message, just timeout due to long processing of that line.

**Comment by derekantrican** [comment]
Peppito - actually, that is an entirely different repository (GAS-ICS-Sync script does not exist in this repo any more)

Please do the following:

1. Go to https://github.com/derekantrican/GAS-ICS-Sync/issues
2. Check to see if any of the issues relate to the problem you're experiencing (on first glance I see https://github.com/derekantrican/GAS-ICS-Sync/issues/39 and https://github.com/derekantrican/GAS-ICS-Sync/issues/46)
3. IF your issue is not one of those, then you can submit a new issue there
