### ISSUE TITLE
ICS/ICAL Sync doesn't remove deleted events

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/Google-Apps-Script-Library#5]
If an event is deleted from the "ics/ical" calendar, the ICS/ICAL sync program doesn't delete the event from the Google Calendar

**Comment by ollisulopuisto** [comment]
Yeah I was thinking about this as well. Would it be too much of a hack to have an option to first wipe the target calendar clean and then copy the entries? Or maybe limit that to a shorter scope, like +7 days or something.

**Comment by derekantrican** [comment]
@ollisulopuisto I don't think that would be too much of a problem, we'd just have to keep track of which events were added to the calendar and store those somewhere for the next time the script runs. This can be done a number of ways, but one way to do "global variables" ("global" as in - "will still be set when you run the program again") is with `PropertiesService`

**Comment by colemanw** [comment]
Not just deleted events, but also updated ones. If the dates, times, title or description changes in an event, this script would need to be smart about that. Deleting and re-adding events every time would achieve the goal, but wouldn't that change the unique identifier of each event during every sync?

**Comment by derekantrican** [comment]
@colemanw Id of which event? The ics event or the Google Calendar event?

**Comment by colemanw** [comment]
Well it would delete and re-add events to gcal continually (potentially every 5 minutes) which means they would not be the "same" events in gcal from one minute to the next. I'm no gcal expert but it seems like that would cause some screwy issues, e.g.

- User edits in gcal (e.g. adding a reminder notification to an event) would disappear.
- The feed coming from gcal would constantly be changing, which might cause any external app reading that feed to create many, many duplicate copies of each event.

**Comment by agentd00nut** [comment]
I've implemented a basic deletion/update feature in #9 

Source feed event ids are now stored in a metadata tag on the event under the "FID"(Feed/Foreign ID) string instead of the description.
When attempting to delete events we first grab a very large time range of events that exist in the calendar.  Then see if their FID tag exists in an array of all the FID tags we saw just now from the feed.
If not we remove it.

Implementing event updates works on the same concept... When an existing calendar events FID was found in the feed, we can start comparing each piece of the event, if they differ update it.

**Comment by derekantrican** [comment]
@agentd00nut Mostly - looks great! I didn't know about the `setTag` method! Please go through my comments that I added to your pull request. One important one: let's leave multiple calendar support for later. I've added issue #10 for this. Discussion can happen there
